export const personalCopy = {
  pt: {
    title: "Um pouco de Samuel", close: "Fechar segredo", collection: "Outros segredos", replay: "Ver de novo", restart: "Jogar de novo", pause: "Jogo pausado enquanto esta aba está oculta.",
    voyage: { title: "Próxima parada: Grand Line.", story: "One Piece é meu anime favorito. Naruto também tem um lugar na lista.", detail: "O chapéu de palha foi parar no planetinha. Ele também ganhou um barco para explorar por aqui.", action: "Levantar as velas" },
    ghosts: { title: "Ghosts, desde a infância.", story: "Michael Jackson é um dos meus cantores favoritos desde criança, e Ghosts é minha música favorita dele.", detail: "Joguei muito The Experience no Wii do meu primo. Comprei controles e um sensor só para voltar a jogar no PC. Também ouço João Gomes, forró, trap BR e gringo e hip-hop.", action: "Mandar um moonwalk" },
    basketball: { title: "Stepback, três pontos, cash.", story: "Joguei basquete por quase quatro anos, como armador e ala-armador. Meu jogo era de shooter.", detail: "Também sou apaixonado por tênis. Ainda tenho meu Kyrie 7 Daybreak.", action: "Arremessar", ready: "Pare o marcador na faixa rosa para acertar. São cinco arremessos.", aiming: "Toque em Arremessar ou use Enter/Espaço na faixa rosa.", swish: "Cash! +3 pontos.", miss: "Bateu no aro. Próxima bola.", end: "Fim da série.", attempts: "Bolas", points: "Pontos", best: "Recorde", assist: "Mira sem movimento", aim: "Mira", left: "À esquerda", center: "No centro", right: "À direita", start: "Iniciar série" },
    blocks: { title: "Só mais uma partida na 1.8.9.", story: "Minecraft foi o jogo que mais joguei na vida, principalmente SkyWars e BedWars na versão 1.8.9.", detail: "Aqui o desafio é construir uma ponte. Complete as três fileiras com os blocos disponíveis, sem deixar buracos.", action: "Girar peça", place: "Colocar peça", undo: "Desfazer", rows: "Fileiras", pieces: "Blocos restantes", won: "Ponte pronta. Partiu outra ilha!", invalid: "Essa peça não cabe aí. Gire ou escolha outro ponto.", cell: "Casa", empty: "vazia", filled: "ocupada", choose: "Selecione o ponto inicial da peça e coloque os blocos. Setas mudam a casa; R gira a peça; Enter coloca.", placed: "Peça colocada.", horizontal: "Horizontal", vertical: "Vertical" },
    valorant: { title: "Valorant: Ascendente 1.", story: "Valorant ocupou boa parte dos meus últimos três anos. Meu pico foi Ascendente 1.", detail: "A insígnia está escondida no treino de mira. Toque nos três alvos para revelá-la.", action: "Reiniciar alvos", target: "Alvo", found: "Ascendente 1 revelado." },
    bahia: { title: "Baiano. Acarajé vem junto.", story: "Sou baiano. Camarão, yakisoba e acarajé estão entre minhas comidas favoritas.", detail: "A bancada também tem um intervalo para comer. Escolha o prato.", foods: ["Acarajé", "Yakisoba", "Camarão"] },
    toddy: { title: "Toddy, meu parceiro.", story: "Tenho um cachorro chamado Toddy. Ele é uma mistura de Yorkshire com Shih-tzu.", detail: "Esta é uma versão desenhada dele. Chame o Toddy para ver o que ele faz com um ossinho.", action: "Chamar Toddy" },
  },
  en: {
    title: "A little more about Samuel", close: "Close secret", collection: "More secrets", replay: "Replay", restart: "Play again", pause: "Game paused while this tab is hidden.",
    voyage: { title: "Next stop: Grand Line.", story: "One Piece is my favourite anime. Naruto is on the list too.", detail: "The little planet found a straw hat and a boat to explore this place.", action: "Set sail" },
    ghosts: { title: "Ghosts, since childhood.", story: "Michael Jackson has been one of my favourite singers since childhood. Ghosts is my favourite song of his.", detail: "I played The Experience on my cousin's Wii a lot. I even bought controllers and a sensor to play it on PC again. I also listen to João Gomes, forró, Brazilian and international trap, and hip-hop.", action: "Do a moonwalk" },
    basketball: { title: "Stepback, three points, cash.", story: "I played basketball for almost four years as a point guard and shooting guard. I was a shooter.", detail: "I'm also into sneakers. I still have my Kyrie 7 Daybreak.", action: "Shoot", ready: "Stop the marker in the pink zone to score. You get five shots.", aiming: "Tap Shoot or use Enter/Space in the pink zone.", swish: "Cash! +3 points.", miss: "Off the rim. Next ball.", end: "End of the round.", attempts: "Shots", points: "Points", best: "Best", assist: "Still aim mode", aim: "Aim", left: "Left", center: "Centre", right: "Right", start: "Start round" },
    blocks: { title: "One more match on 1.8.9.", story: "Minecraft is the game I've played the most, especially SkyWars and BedWars on version 1.8.9.", detail: "Build a bridge here. Fill all three rows with the available blocks and leave no gaps.", action: "Rotate piece", place: "Place piece", undo: "Undo", rows: "Rows", pieces: "Blocks left", won: "Bridge complete. On to the next island!", invalid: "That piece won't fit. Rotate it or choose another spot.", cell: "Cell", empty: "empty", filled: "filled", choose: "Choose the start of the piece and place it. Arrows move selection; R rotates; Enter places.", placed: "Piece placed.", horizontal: "Horizontal", vertical: "Vertical" },
    valorant: { title: "Valorant: Ascendant 1.", story: "I've played a lot of Valorant over the past three years. My peak was Ascendant 1.", detail: "The badge is hidden in aim practice. Tap the three targets to reveal it.", action: "Reset targets", target: "Target", found: "Ascendant 1 revealed." },
    bahia: { title: "From Bahia, with acarajé.", story: "I'm from Bahia. Shrimp, yakisoba and acarajé are some of my favourite foods.", detail: "There's a food break at this workbench too. Pick a dish.", foods: ["Acarajé", "Yakisoba", "Shrimp"] },
    toddy: { title: "Toddy, my buddy.", story: "My dog is called Toddy. He's a Yorkshire Terrier and Shih Tzu mix.", detail: "This is a drawn version of him. Call Toddy over to see what he does with a bone.", action: "Call Toddy" },
  },
} as const;
