export const personalCopy = {
  pt: {
    close: "Voltar ao portfólio", restart: "Jogar de novo", pause: "Jogo pausado.",
    basketball: { title: "Stepback. Cash.", action: "Arremessar", ready: "Pare o marcador na faixa rosa. Cinco bolas, três pontos por acerto.", aiming: "Toque na bola ou em Arremessar. Espaço ou Enter arremessam; segurar a tecla não repete o lance.", swish: "Cash! +3", miss: "No aro. Próxima bola.", flying: "…", end: "Fim da série.", attempts: "Bolas", points: "Pontos", best: "Recorde", assist: "Mira sem movimento", aim: "Mira", left: "Esquerda", center: "Centro", right: "Direita", start: "Iniciar série" },
    blocks: { title: "Saltos na 1.8.9", action: "Segure para mirar", release: "Solte para saltar", jump: "Saltar", jumps: "Saltos", lives: "Vidas", best: "Recorde", assist: "Modo tranquilo", ready: "Segure o botão. Solte quando a sombra chegar à próxima ilha. No teclado, segure Espaço ou Enter.", calmReady: "Um salto por vez, sem precisar acertar o tempo.", landed: "Boa! Próxima ilha.", miss: "Caiu no vazio. Tente de novo.", won: "Chegou à cama!", over: "Fim da partida. Mais uma?", flying: "…" },
    moment: { voyage: "Um chapéu de palha e uma viagem no Going Merry.", ghosts: "Chapéu, luva e moonwalk: um tributo ao Michael.", toddy: "Toddy veio buscar um ossinho.", aim: "Acerte as três miras em {seconds} segundos. O tempo começa ao iniciar.", close: "Encerrar descoberta", target: "Alvo", found: "Três acertos. Insígnia revelada.", start: "Iniciar treino", retry: "Tentar novamente", failed: "Tempo esgotado. Acerte as três miras na próxima tentativa.", aimPlaying: "Acerte as três miras antes de o tempo acabar.", timeLeft: "Tempo restante", untimed: "Sem limite de tempo", untimedShort: "Sem limite", untimedHelp: "Treino livre: acerte as três miras no seu ritmo." },
  },
  en: {
    close: "Back to the portfolio", restart: "Play again", pause: "Game paused.",
    basketball: { title: "Stepback. Cash.", action: "Shoot", ready: "Stop the marker in the pink zone. Five shots, three points per basket.", aiming: "Tap the ball or Shoot. Space or Enter shoots; holding the key does not repeat a shot.", swish: "Cash! +3", miss: "Off the rim. Next ball.", flying: "…", end: "End of the round.", attempts: "Shots", points: "Points", best: "Best", assist: "Still aim mode", aim: "Aim", left: "Left", center: "Centre", right: "Right", start: "Start round" },
    blocks: { title: "1.8.9 sky jumps", action: "Hold to aim", release: "Release to jump", jump: "Jump", jumps: "Jumps", lives: "Lives", best: "Best", assist: "Calm mode", ready: "Hold the button. Release when the shadow reaches the next island. On a keyboard, hold Space or Enter.", calmReady: "One jump at a time, with no timing required.", landed: "Nice! Next island.", miss: "Into the void. Try again.", won: "Made it to the bed!", over: "Round over. One more?", flying: "…" },
    moment: { voyage: "A straw hat and a voyage on the Going Merry.", ghosts: "A hat, a glove and a moonwalk: a tribute to Michael.", toddy: "Toddy came to fetch a bone.", aim: "Hit all three targets in {seconds} seconds. The clock starts when you begin.", close: "End discovery", target: "Target", found: "Three hits. Badge revealed.", start: "Start practice", retry: "Try again", failed: "Time is up. Hit all three targets on your next attempt.", aimPlaying: "Hit all three targets before time runs out.", timeLeft: "Time remaining", untimed: "No time limit", untimedShort: "Untimed", untimedHelp: "Free practice: hit all three targets at your own pace." },
  },
} as const;
